version: '3.8'

services:
  mysql:
    image: mysql:8.4.0
    restart: always
    container_name: mysql_wordpress
    networks:
      - wordpress-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - ./wordpress_data/mysql_db:/var/lib/mysql

  wordpress:
    image: wordpress:php8.3
    restart: always
    container_name: wordpress_docker
    depends_on:
      - mysql
    networks:
      - wordpress-network
    environment:
      WORDPRESS_DB_HOST: mysql_wordpress:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
    volumes:
      - ./wordpress_data/WordPress:/var/www/html

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    container_name: phpmyadmin
    depends_on:
      - mysql
    networks:
      - wordpress-network
    environment:
      PMA_HOST: mysql_wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"

networks:
  wordpress-network:
